### ISSUE TITLE
`setup.py test` is bad practice

### ISSUE THREAD

**Issue by jamesmyatt** [audreyfeldroy/cookiecutter-pypackage#500]
`setup.py test` is deprecated and will be removed one day: https://github.com/pypa/setuptools/issues/1684
`pytest-runner` is no longer recommended: https://github.com/pytest-dev/pytest-runner/issues/50

The project should be updated to avoid these "smells".

**Comment by graingert** [comment]
It might also be worth pyproject.toml PEP517/PEP518 support too

**Comment by pganssle** [comment]
`pyproject.toml` is orthogonal to setup.py. This project should definitely add a `pyproject.toml`, but I'm not sure I'd recommend switching it over to a different build backend.

**Comment by ChadBailey** [comment]
Please see my PR https://github.com/audreyr/cookiecutter-pypackage/pull/544 which should remove all references to `setup.py test`

**Comment by trybik** [comment]
> Please see my PR #544 which should remove all references to `setup.py test`

In accordance with [deprecation notice of pytest-runner](https://pypi.org/project/pytest-runner/):

> It is recommended that you:
>
> * Remove ‘pytest-runner’ from your ‘setup_requires’, preferably removing the setup_requires option.
> * Remove ‘pytest’ and any other testing requirements from ‘tests_require’, preferably removing the setup_requires option.`

Both are still in [{{cookiecutter.project_slug}}/setup.py](https://github.com/audreyr/cookiecutter-pypackage/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/setup.py) and not in PR #544.

**Comment by ChadBailey** [comment]
Good catch, thanks for pointing out this omission. I'll update if I find the time but feel free to do so yourself

**Comment by phith0n** [comment]
I ran into the same problem.

**Comment by pydanny** [comment]
Thanks everyone for their commentary. We're in the midst of removing python setup.py test. 😄
