### ISSUE TITLE
Error with the "make clean-build" command

### ISSUE THREAD

**Issue by williamcanin** [audreyfeldroy/cookiecutter-pypackage#564]
* Date you used Cookiecutter PyPackage: 2020/02/05
* Cookiecutter version used, if any:
* Python version, if any: 3.8
* Operating System: Linux

### Description

When we activate the virtual machine in the project; we installed the requirements and, we installed the package with "**make install**", right after that when we are going to do a cleaning with the "**make clean**" command, an error is obtained in the "**clean-build**" section of the **Makefile** file.

### What I Did

```
make clean  
rm -fr build/
rm -fr dist/
rm -fr .eggs/
find . -name '*.egg-info' -exec rm -fr {} +
find . -name '*.egg' -exec rm -f {} +
rm: unable to remove './venv/lib/python3.8/site-packages/python_boilerplate-0.1.0-py3.8.egg': It is a directory
make: *** [Makefile:36: clean-build] Error 1
```

This is because in line 6 (find. -name '* .egg' -exec rm -f {} +), the command trying to remove a directory containing "**egg**" in my virtual machine (_venv_) folder. Then the error arises because it does not have the "**r**" flag for removing directories in the command.

My suggestion is to ignore the directory of the virtual machine in the "**_find_**" commands, like this:

```
find . '!' -path './venv/*' -name '*.egg' -exec rm -f {} +
```

**Comment by PsiACE** [comment]
Got it, I saw your pr, let's discuss it in #562
