### ISSUE TITLE
Plans to use black? Are pull requests welcome?

### ISSUE THREAD

**Issue by AndreMiras** [audreyfeldroy/cookiecutter-pypackage#575]
Is there plan to use black https://github.com/psf/black ?
If so are pull requests integrating it welcome?

**Comment by PsiACE** [comment]
Very welcome. Please note that it needs to be given as an option.

**Comment by AndreMiras** [comment]
Great, this is addressed in https://github.com/audreyr/cookiecutter-pypackage/pull/576 I tried to keep it as simple as possible for the first iteration
