### ISSUE TITLE
This repo looks dead

### ISSUE THREAD

**Issue by apehex** [audreyfeldroy/cookiecutter-pypackage#605]
* Date you used Cookiecutter PyPackage: 2020-09-12
* Cookiecutter version used, if any: 0.5.10
* Python version, if any: 3.8.2
* Operating System: debian

### Description

I see tons of PRs addressing current issues, without answer after years.
Some tools used by 'cookiecutter-pypackage' are deprecated and / or clunky.

### What I Did

Obviously a fork.
Still it isn't satisfying, as contributors have no common ground to start on, we all have to make our separate way from here.

```
Am I the only one left using cookiecutters in 2020?
Any person eager to see this move forward?
```

**Comment by ammaraziz** [comment]
Yes. As a beginner who was *just* referred to this repo as a good start for python project setup, yes!

**Comment by Zeitsperre** [comment]
I would be curious to hear from @audreyfeldroy if there could be a means of developing a PR checklist. I like the idea of having main branch for very general fixes that ALL forks can gain from, mine included.

Perhaps adding a few maintainers and developing a contributor code might help with this process?

**Comment by tmcclintock** [comment]
Agreed with the above. This repo is important enough to have new stewardship.

**Comment by Zethson** [comment]
@moodule @ammaraziz @Zeitsperre @tmcclintock we integrated and greatly improved this template into cookietemple (https://github.com/cookiejar/cookietemple/).
The cli-python template resembles this template with Github Actions, Github Pages and much more.
Maybe this is for you?

**Comment by Zeitsperre** [comment]
@Zethson Very interesting. Thanks for letting us know!

**Comment by Zethson** [comment]
@Zeitsperre Glad you find it interesting!
Since you mentioned in this issue that you were interested in adding fixes I would like to invite you to contribute your fixes to cookietemple's cli-python template.
We are very active and will certainly interact with you and get your fixes into the template.
