### ISSUE TITLE
pytest throws warning (Unknown config option: collect_ignore)

### ISSUE THREAD

**Issue by geozeke** [audreyfeldroy/cookiecutter-pypackage#608]
This package is fantastic! Thank you so much for all the hard work on it.

* Date you used Cookiecutter PyPackage: 10/18/20
* Cookiecutter version used, if any: 1.7.2
* Python version, if any: 3.8.5
* Operating System: Ubuntu 20.04

### Description

When attempting to run `make test`, pytest throws a warning. It appears to have trouble with this section in `setup.cfg`:

```
[tool:pytest]
collect_ignore = ['setup.py']
```

Which is curious, because `collect_ignore` is an environment variable called out in the pytest documentation.

### What I Did

Ran a test on my project with: `make test`

```
(pydev) ➜  mypackage make test                      
pytest
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/----/shares/Repos/mypackage, configfile: setup.cfg
collected 11 items                                                             

tests/test_mypackage.py ...........                                      [100%]

=============================== warnings summary ===============================
../pydev/lib/python3.8/site-packages/_pytest/config/__init__.py:1230
  /home/----/shares/Repos/pydev/lib/python3.8/site-packages/_pytest/config/__init__.py:1230: PytestConfigWarning: Unknown config option: collect_ignore
  
    self._warn_or_fail_if_strict("Unknown config option: {}\n".format(key))

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 11 passed, 1 warning in 0.55s =========================
(pydev) ➜  mypackage 

```

**Comment by cauliyang** [comment]
I meet the same issue!

**Comment by genzj** [comment]
Here is a workaround. Just remove the `collect_ignore` from `setup.cfg` and specify it via cli args instead, e.g. `pytest --ignore=setup.py`

**Comment by lene** [comment]
Same issue here with Python 3.8.6, pytest-6.2.1

**Comment by sbliven** [comment]
Yep, this seems to have been removed from pytest. The setup.cfg template should be adjusted.

**Comment by dcmoura** [comment]
Workaround:

Remove the `collect_ignore` entry.
Add command line options to pytest using `addopts`:

```
[tool:pytest]
addopts = --ignore=setup.py
```
