### ISSUE TITLE
broken link in readme

### ISSUE THREAD

**Issue by zillionare** [audreyfeldroy/cookiecutter-pypackage#658]
I am the author of project zillionare/cookiecutter-pypackage, and the template has been mentioned in readme:
```
[zillionare/cookiecutter-pypackage](https://zillionare.github.io/cookiecutter-pypackage/): A template containing [Poetry](https://python-poetry.org/), [Mkdocs](https://pypi.org/project/mkdocs/), Github CI and many more. It's a template and a package also (can be installed with pip)
```

recently I have made update to the template rename the project as python-project-wizard, so the link is broken. I have submitted pull request to fix this broken link, please approve the merge.

Thanks!

**Comment by Enrikaa** [comment]
@zillionare closed the pull request because implemented a redirect, making the README link update unnecessary.

https://github.com/audreyfeldroy/cookiecutter-pypackage/pull/657
